intervalo_horas: 0.5
resumen_interval_hours: 12

notificaciones:
  email_destino: "edua56621636@gmail.com"

cuentas:
  - nombre: "Eduardo Pérez"
    identificador: "ESP326CU6B42408511646445"
    año_nacimiento: "2005"
    email_notif: "edua56621636@gmail.com"

  - nombre: "Lucía Soler"
    identificador: "ESP326CUDB42108243467929"
    año_nacimiento: "2006"
    email_notif: "edua56621636@gmail.com"

postgres:
  enabled: true






